In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Downloads/edtech_student_learning_data.csv")

In [4]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0

In [6]:
#2. Display the first 10 records of the dataset.
df[:10]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0
5,1006,Student_6,Female,Pune,2024-09-18,Generative AI,Weekend,120,79,64,98,57,2.6,30,Placed,6,65.83,305730.0
6,1007,Student_7,Male,Mumbai,2024-02-22,Data Analytics,Weekend,120,112,93,89,94,3.2,29,Placed,6,93.33,707137.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.3,14,Placed,6,90.83,1053790.0
8,1009,Student_9,Male,Mumbai,2024-05-05,AI & ML,Weekend,120,83,75,61,96,2.6,19,Placed,8,69.17,502210.0
9,1010,Student_10,Female,Delhi,2024-08-22,Data Analytics,Weekday,120,118,70,50,89,4.2,26,Not Placed,8,98.33,NaN

In [7]:
#3. Display the last 5 records of the dataset.
df.tail()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
500,1452,Student_452,Female,Mumbai,2024-03-07,Generative AI,Weekday,120,68,84,84,58,2.2,19,Not Placed,8,56.67,NaN
501,1276,Student_276,Female,Hyderabad,2024-10-15,Generative AI,Weekday,120,95,92,81,91,3.2,16,Not Placed,8,79.17,NaN
502,1210,Student_210,Male,Bangalore,2024-04-04,AI & ML,Weekday,120,75,40,84,77,2.4,19,Placed,5,62.50,750043.0
503,1178,Student_178,Male,Delhi,2024-01-20,Generative AI,Weekday,120,80,97,92,66,4.7,33,Placed,5,66.67,890611.0
504,1397,Student_397,Female,Mumbai,2024-05-27,Generative AI,Weekend,120,101,66,83,66,3.6,25,Placed,7,84.17,1003022.0

In [10]:
#4. Check the shape of the dataset.
df[:]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1452,Student_452,Female,Mumbai,2024-03-07,Generative AI,Weekday,120,68,84,84,58,2.2,19,Not Placed,8,56.67,NaN
501,1276,Student_276,Female,Hyderabad,2024-10-15,Generative AI,Weekday,120,95,92,81,91,3.2,16,Not Placed,8,79.17,NaN
502,1210,Student_210,Male,Bangalore,2024-04-04,AI & ML,Weekday,120,75,40,84,77,2.4,19,Placed,5,62.50,750043.0
503,1178,Student_178,Male,Delhi,2024-01-20,Generative AI,Weekday,120,80,97,92,66,4.7,33,Placed,5,66.67,890611.0
504,1397,Student_397,Female,Mumbai,2024-05-27,Generative AI,Weekend,120,101,66,83,66,3.6,25,Placed,7,84.17,1003022.0

In [12]:
#5. Display all column names along with their data types.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         505 non-null    int64
 1   student_name       505 non-null    object
 2   gender             505 non-null    object
 3   city               505 non-null    object
 4   enrollment_date    505 non-null    object
 5   course             505 non-null    object
 6   batch_type         505 non-null    object
 7   total_sessions     505 non-null    int64
 8   sessions_attended  505 non-null    int64
 9   avg_quiz_score     505 non-null    int64
 10  assignment_score   505 non-null    int64
 11  project_score      505 non-null    int64
 12  final_rating       477 non-null    float64
 13  learning_hours     505 non-null    int64
 14  placement_status   505 non-null    object
 15  feedback_score     505 non-null    int64
 16  attendance_pct     505 non-null    float64
 17  salary_offered     336 non-null    float64
dtypes: float64(3), int64(8), object(7)
memory usage: 71.1+ KB

In [13]:
#6. Generate summary statistics for all numerical columns.
df.describe()

,student_id,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,feedback_score,attendance_pct,salary_offered
count,505.000000,505.0,505.000000,505.000000,505.000000,505.000000,477.000000,505.000000,505.000000,505.000000,3.360000e+02
mean,1251.015842,120.0,88.102970,69.601980,71.984158,75.287129,3.535220,22.128713,7.041584,73.419149,7.701324e+05
std,144.242011,0.0,17.087232,17.137226,15.777337,14.678794,0.862365,9.924180,1.370122,14.239418,2.656396e+05
min,1001.000000,120.0,60.000000,40.000000,45.000000,50.000000,2.000000,5.000000,5.000000,50.000000,3.005150e+05
25%,1127.000000,120.0,73.000000,56.000000,58.000000,62.000000,2.800000,14.000000,6.000000,60.830000,5.442040e+05
50%,1251.000000,120.0,88.000000,69.000000,72.000000,76.000000,3.600000,23.000000,7.000000,73.330000,7.788115e+05
75%,1376.000000,120.0,103.000000,84.000000,86.000000,88.000000,4.300000,31.000000,8.000000,85.830000,1.003022e+06
max,1500.000000,120.0,119.000000,99.000000,99.000000,99.000000,5.000000,39.000000,9.000000,99.170000,1.199092e+06

In [15]:
#7. Identify columns that contain missing values.
df.isna()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
#8. Count the number of missing values in each column.
df.isna().sum()

student_id             0
student_name           0
gender                 0
city                   0
enrollment_date        0
course                 0
batch_type             0
total_sessions         0
sessions_attended      0
avg_quiz_score         0
assignment_score       0
project_score          0
final_rating          28
learning_hours         0
placement_status       0
feedback_score         0
attendance_pct         0
salary_offered       169
dtype: int64

In [19]:
#9. Calculate the percentage of missing values in the final_rating column.
df["final_rating"].isna().mean()*100

np.float64(5.544554455445545)

In [23]:
#10. Fill missing values in the final_rating column using the mean.
df['final_rating'].fillna(df['final_rating'].mean(), inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_12028\2986504576.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['final_rating'].fillna(df['final_rating'].mean(), inplace=True)

In [25]:
#11. Verify that missing values in final_rating are handled.
df["final_rating"].isna().sum()

np.int64(0)

In [28]:
#12. Check whether duplicate records exist in the dataset.
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
500     True
501     True
502     True
503     True
504     True
Length: 505, dtype: bool

In [30]:
#13. Count the total number of duplicate rows.
df.duplicated().sum()

np.int64(5)

In [31]:
#14. Display all duplicate records.
df[df.duplicated()]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
500,1452,Student_452,Female,Mumbai,2024-03-07,Generative AI,Weekday,120,68,84,84,58,2.2,19,Not Placed,8,56.67,NaN
501,1276,Student_276,Female,Hyderabad,2024-10-15,Generative AI,Weekday,120,95,92,81,91,3.2,16,Not Placed,8,79.17,NaN
502,1210,Student_210,Male,Bangalore,2024-04-04,AI & ML,Weekday,120,75,40,84,77,2.4,19,Placed,5,62.50,750043.0
503,1178,Student_178,Male,Delhi,2024-01-20,Generative AI,Weekday,120,80,97,92,66,4.7,33,Placed,5,66.67,890611.0
504,1397,Student_397,Female,Mumbai,2024-05-27,Generative AI,Weekend,120,101,66,83,66,3.6,25,Placed,7,84.17,1003022.0

In [37]:
#15. Remove duplicate records from the dataset.
df.drop_duplicates(inplace=True)

In [38]:
#16. Verify the dataset size after removing duplicates.
df[:]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.70000,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.50000,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.60000,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.70000,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.10000,23,Placed,9,84.17,970105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,Student_496,Male,Hyderabad,2024-12-29,Data Science,Weekday,120,86,94,97,57,3.10000,14,Placed,7,71.67,572544.0
496,1497,Student_497,Male,Hyderabad,2024-10-06,Generative AI,Weekday,120,61,88,53,72,3.70000,28,Placed,5,50.83,834633.0
497,1498,Student_498,Female,Bangalore,2024-03-21,Data Analytics,Weekday,120,94,94,53,63,3.40000,39,Placed,7,78.33,333896.0
498,1499,Student_499,Male,Mumbai,2024-07-20,Data Science,Weekday,120,77,72,48,76,3.53522,27,Placed,8,64.17,778646.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.80000,21,Placed,7,60.83,1115331.0

In [41]:
#17. Find the number of unique values in the city column.
df["city"].nunique()

6

In [42]:
#18. Find the number of unique values in the course column.
df["course"].nunique()

4

In [43]:
#19. Display all unique cities present in the dataset.
df["city"].unique()

array(['Hyderabad', 'Pune', 'Delhi', 'Mumbai', 'Chennai', 'Bangalore'],
      dtype=object)

In [45]:
#20. Count the number of students in each city.
df["city"].value_counts()

city
Hyderabad    99
Mumbai       93
Pune         87
Bangalore    81
Chennai      73
Delhi        67
Name: count, dtype: int64

In [46]:
#21. Count the number of students enrolled in each course.
df["course"].value_counts()

course
Data Analytics    143
Data Science      128
AI & ML           125
Generative AI     104
Name: count, dtype: int64

In [51]:
#22. Identify the course with the highest student enrollment.
df["course"].value_counts().max()

143

In [59]:
#23. Count the number of students who are placed and not placed.
df["placement_status"].value_counts()

placement_status
Placed        333
Not Placed    167
Name: count, dtype: int64

In [60]:
#24. Filter students whose attendance percentage is greater than 80.
df[df["attendance_pct"]>80]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0
6,1007,Student_7,Male,Mumbai,2024-02-22,Data Analytics,Weekend,120,112,93,89,94,3.2,29,Placed,6,93.33,707137.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.3,14,Placed,6,90.83,1053790.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,1475,Student_475,Male,Delhi,2024-04-21,Data Science,Weekend,120,101,99,85,83,2.6,12,Placed,8,84.17,471349.0
475,1476,Student_476,Female,Chennai,2024-02-05,Data Analytics,Weekday,120,97,99,99,94,3.6,33,Placed,9,80.83,855839.0
477,1478,Student_478,Female,Mumbai,2024-07-06,AI & ML,Weekend,120,104,88,73,87,3.8,14,Placed,5,86.67,749813.0
481,1482,Student_482,Female,Mumbai,2024-07-15,Generative AI,Weekend,120,101,63,56,66,3.6,30,Placed,9,84.17,309637.0
488,1489,Student_489,Male,Chennai,2024-10-19,Generative AI,Weekend,120,111,70,49,75,3.3,26,Not Placed,7,92.50,NaN

In [64]:
#25. Filter students who attended fewer than 70 sessions.
df[df["attendance_pct"]<70]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.60000,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.70000,5,Not Placed,8,59.17,NaN
5,1006,Student_6,Female,Pune,2024-09-18,Generative AI,Weekend,120,79,64,98,57,2.60000,30,Placed,6,65.83,305730.0
8,1009,Student_9,Male,Mumbai,2024-05-05,AI & ML,Weekend,120,83,75,61,96,2.60000,19,Placed,8,69.17,502210.0
22,1023,Student_23,Female,Chennai,2024-07-13,Generative AI,Weekend,120,82,52,70,87,4.80000,14,Not Placed,5,68.33,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,1493,Student_493,Male,Mumbai,2024-02-22,Data Analytics,Weekday,120,80,84,47,83,3.70000,32,Placed,8,66.67,323834.0
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.10000,9,Placed,8,50.83,867354.0
496,1497,Student_497,Male,Hyderabad,2024-10-06,Generative AI,Weekday,120,61,88,53,72,3.70000,28,Placed,5,50.83,834633.0
498,1499,Student_499,Male,Mumbai,2024-07-20,Data Science,Weekday,120,77,72,48,76,3.53522,27,Placed,8,64.17,778646.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.80000,21,Placed,7,60.83,1115331.0

In [65]:
#26. Filter students with an average quiz score above 85.
df[df["avg_quiz_score"]<85]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.70000,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.50000,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.60000,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.70000,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.10000,23,Placed,9,84.17,970105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,1493,Student_493,Male,Mumbai,2024-02-22,Data Analytics,Weekday,120,80,84,47,83,3.70000,32,Placed,8,66.67,323834.0
493,1494,Student_494,Female,Delhi,2024-12-20,Generative AI,Weekday,120,94,75,88,88,3.90000,36,Placed,8,78.33,596618.0
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.10000,9,Placed,8,50.83,867354.0
498,1499,Student_499,Male,Mumbai,2024-07-20,Data Science,Weekday,120,77,72,48,76,3.53522,27,Placed,8,64.17,778646.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.80000,21,Placed,7,60.83,1115331.0

In [67]:
#27. Filter students enrolled in the Data Science course.
df[df["course"]=="Data Science"]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.60000,8,Placed,5,60.83,501904.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.30000,14,Placed,6,90.83,1053790.0
10,1011,Student_11,Male,Chennai,2024-02-12,Data Science,Weekday,120,102,53,48,61,4.60000,25,Not Placed,7,85.00,NaN
13,1014,Student_14,Male,Mumbai,2024-09-05,Data Science,Weekday,120,109,55,91,96,3.70000,34,Placed,6,90.83,645430.0
18,1019,Student_19,Female,Pune,2024-01-08,Data Science,Weekend,120,115,74,58,78,2.90000,11,Placed,8,95.83,1000399.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,1488,Student_488,Female,Pune,2024-09-17,Data Science,Weekday,120,66,92,65,51,2.20000,27,Placed,7,55.00,797760.0
489,1490,Student_490,Male,Pune,2024-09-12,Data Science,Weekend,120,73,75,92,62,4.10000,6,Placed,7,60.83,667747.0
490,1491,Student_491,Female,Bangalore,2024-08-09,Data Science,Weekday,120,68,58,64,96,3.40000,35,Placed,6,56.67,1097955.0
495,1496,Student_496,Male,Hyderabad,2024-12-29,Data Science,Weekday,120,86,94,97,57,3.10000,14,Placed,7,71.67,572544.0
498,1499,Student_499,Male,Mumbai,2024-07-20,Data Science,Weekday,120,77,72,48,76,3.53522,27,Placed,8,64.17,778646.0

In [68]:
#28. Filter students who are not placed and attended more than 75 sessions.
df[(df["placement_status"]=="Not Placed" ) & (df["sessions_attended"]>75)]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.50000,33,Not Placed,8,91.67,NaN
9,1010,Student_10,Female,Delhi,2024-08-22,Data Analytics,Weekday,120,118,70,50,89,4.20000,26,Not Placed,8,98.33,NaN
10,1011,Student_11,Male,Chennai,2024-02-12,Data Science,Weekday,120,102,53,48,61,4.60000,25,Not Placed,7,85.00,NaN
15,1016,Student_16,Male,Mumbai,2024-07-01,Data Analytics,Weekday,120,116,85,59,90,3.60000,32,Not Placed,7,96.67,NaN
16,1017,Student_17,Female,Mumbai,2024-12-01,AI & ML,Weekend,120,98,91,50,68,3.40000,5,Not Placed,9,81.67,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,1465,Student_465,Female,Chennai,2024-06-30,Data Science,Weekday,120,102,94,74,80,3.53522,24,Not Placed,9,85.00,NaN
469,1470,Student_470,Female,Hyderabad,2024-09-19,Generative AI,Weekday,120,111,73,52,52,3.60000,24,Not Placed,6,92.50,NaN
473,1474,Student_474,Female,Delhi,2024-05-26,Data Analytics,Weekend,120,108,70,66,81,3.70000,15,Not Placed,6,90.00,NaN
480,1481,Student_481,Female,Mumbai,2024-10-29,Data Science,Weekday,120,83,61,74,89,3.90000,36,Not Placed,7,69.17,NaN
488,1489,Student_489,Male,Chennai,2024-10-19,Generative AI,Weekend,120,111,70,49,75,3.30000,26,Not Placed,7,92.50,NaN

In [70]:
#29. Filter students belonging to Pune, Bangalore, or Hyderabad.
df[df["city"].isin(["Pune","Bangalore","Hyderabad"])]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
5,1006,Student_6,Female,Pune,2024-09-18,Generative AI,Weekend,120,79,64,98,57,2.6,30,Placed,6,65.83,305730.0
18,1019,Student_19,Female,Pune,2024-01-08,Data Science,Weekend,120,115,74,58,78,2.9,11,Placed,8,95.83,1000399.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.1,9,Placed,8,50.83,867354.0
495,1496,Student_496,Male,Hyderabad,2024-12-29,Data Science,Weekday,120,86,94,97,57,3.1,14,Placed,7,71.67,572544.0
496,1497,Student_497,Male,Hyderabad,2024-10-06,Generative AI,Weekday,120,61,88,53,72,3.7,28,Placed,5,50.83,834633.0
497,1498,Student_498,Female,Bangalore,2024-03-21,Data Analytics,Weekday,120,94,94,53,63,3.4,39,Placed,7,78.33,333896.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.8,21,Placed,7,60.83,1115331.0

In [71]:
#30. Filter students enrolled in AI & ML or Generative AI courses
df[(df["course"]=="AI & ML") | (df["course"]=="Generative AI")]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0
5,1006,Student_6,Female,Pune,2024-09-18,Generative AI,Weekend,120,79,64,98,57,2.6,30,Placed,6,65.83,305730.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,1489,Student_489,Male,Chennai,2024-10-19,Generative AI,Weekend,120,111,70,49,75,3.3,26,Not Placed,7,92.50,NaN
493,1494,Student_494,Female,Delhi,2024-12-20,Generative AI,Weekday,120,94,75,88,88,3.9,36,Placed,8,78.33,596618.0
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.1,9,Placed,8,50.83,867354.0
496,1497,Student_497,Male,Hyderabad,2024-10-06,Generative AI,Weekday,120,61,88,53,72,3.7,28,Placed,5,50.83,834633.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.8,21,Placed,7,60.83,1115331.0

In [72]:
#31. Filter students whose average quiz score lies between 60 and 80.
df[df["avg_quiz_score"].between(60,80)]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.70000,5,Not Placed,8,59.17,NaN
5,1006,Student_6,Female,Pune,2024-09-18,Generative AI,Weekend,120,79,64,98,57,2.60000,30,Placed,6,65.83,305730.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.30000,14,Placed,6,90.83,1053790.0
8,1009,Student_9,Male,Mumbai,2024-05-05,AI & ML,Weekend,120,83,75,61,96,2.60000,19,Placed,8,69.17,502210.0
9,1010,Student_10,Female,Delhi,2024-08-22,Data Analytics,Weekday,120,118,70,50,89,4.20000,26,Not Placed,8,98.33,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,1489,Student_489,Male,Chennai,2024-10-19,Generative AI,Weekend,120,111,70,49,75,3.30000,26,Not Placed,7,92.50,NaN
489,1490,Student_490,Male,Pune,2024-09-12,Data Science,Weekend,120,73,75,92,62,4.10000,6,Placed,7,60.83,667747.0
493,1494,Student_494,Female,Delhi,2024-12-20,Generative AI,Weekday,120,94,75,88,88,3.90000,36,Placed,8,78.33,596618.0
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.10000,9,Placed,8,50.83,867354.0
498,1499,Student_499,Male,Mumbai,2024-07-20,Data Science,Weekday,120,77,72,48,76,3.53522,27,Placed,8,64.17,778646.0

In [73]:
#32. Filter students whose assignment score lies between 70 and 90.
df[df["assignment_score"].between(70,90)]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
6,1007,Student_7,Male,Mumbai,2024-02-22,Data Analytics,Weekend,120,112,93,89,94,3.2,29,Placed,6,93.33,707137.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.3,14,Placed,6,90.83,1053790.0
14,1015,Student_15,Female,Delhi,2024-05-30,Data Analytics,Weekend,120,88,93,71,64,3.9,29,Placed,7,73.33,1128411.0
20,1021,Student_21,Female,Pune,2024-07-02,AI & ML,Weekday,120,102,45,83,89,3.7,23,Not Placed,6,85.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,1485,Student_485,Male,Delhi,2024-07-13,Data Science,Weekend,120,65,69,90,65,3.8,35,Not Placed,8,54.17,NaN
491,1492,Student_492,Male,Chennai,2024-08-13,Data Analytics,Weekday,120,74,87,81,80,2.3,15,Placed,8,61.67,1155121.0
493,1494,Student_494,Female,Delhi,2024-12-20,Generative AI,Weekday,120,94,75,88,88,3.9,36,Placed,8,78.33,596618.0
494,1495,Student_495,Male,Pune,2024-12-07,AI & ML,Weekend,120,61,69,77,52,4.1,9,Placed,8,50.83,867354.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.8,21,Placed,7,60.83,1115331.0

In [74]:
#33. Filter students whose learning hours lie between 10 and 25.
df[df["learning_hours"].between(10,25)]

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0
7,1008,Student_8,Male,Chennai,2024-07-23,Data Science,Weekend,120,109,72,77,72,4.3,14,Placed,6,90.83,1053790.0
8,1009,Student_9,Male,Mumbai,2024-05-05,AI & ML,Weekend,120,83,75,61,96,2.6,19,Placed,8,69.17,502210.0
10,1011,Student_11,Male,Chennai,2024-02-12,Data Science,Weekday,120,102,53,48,61,4.6,25,Not Placed,7,85.00,NaN
18,1019,Student_19,Female,Pune,2024-01-08,Data Science,Weekend,120,115,74,58,78,2.9,11,Placed,8,95.83,1000399.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,1480,Student_480,Female,Mumbai,2024-01-02,Data Science,Weekday,120,89,58,92,51,4.2,17,Placed,7,74.17,686486.0
485,1486,Student_486,Female,Mumbai,2024-04-28,AI & ML,Weekday,120,62,97,94,87,2.5,22,Placed,5,51.67,716704.0
491,1492,Student_492,Male,Chennai,2024-08-13,Data Analytics,Weekday,120,74,87,81,80,2.3,15,Placed,8,61.67,1155121.0
495,1496,Student_496,Male,Hyderabad,2024-12-29,Data Science,Weekday,120,86,94,97,57,3.1,14,Placed,7,71.67,572544.0
499,1500,Student_500,Female,Pune,2024-06-06,AI & ML,Weekday,120,73,57,79,78,3.8,21,Placed,7,60.83,1115331.0

In [78]:
#34. Create a new column total_score as the sum of quiz, assignment, and project scores.
df['total_score'] = df['avg_quiz_score'] + df['assignment_score'] + df['project_score']

In [79]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered,total_score
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0,221
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN,233
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0,194
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN,236
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0,146

In [80]:
#35. Create a new column attendance_flag based on attendance percentage
def attendance_flag(x):
    if x>=75:
        return 'green flag'
    else:
        return "Red flag"

df["attendance_flag"]=df["attendance_pct"].apply(attendance_flag)

In [81]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0,221,green flag
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN,233,green flag
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0,194,Red flag
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN,236,Red flag
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0,146,green flag

In [84]:
#36. Create a new column learning_intensity based on learning hours
def learning_intensity(x):
    if x>40:
        return"High"
    elif x>=20:
        return"medium"
    else:
        return"low"
df["learning_intensity"]=df["learning_hours"].apply(learning_intensity)

In [85]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,66,3.7,6,Placed,7,90.00,738963.0,221,green flag,low
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,83,4.5,33,Not Placed,8,91.67,NaN,233,green flag,medium
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,73,3.6,8,Placed,5,60.83,501904.0,194,Red flag,low
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,81,2.7,5,Not Placed,8,59.17,NaN,236,Red flag,low
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,50,2.1,23,Placed,9,84.17,970105.0,146,green flag,medium

In [86]:
#37. Classify students based on total_score using apply().
def classify_score(x):
    if x>=200:
        return"Excellent"
    elif x>=150:
        return"Average"
    else:
        return"Poor"
df["Classify_students"]=df["total_score"].apply(classify_score)

In [87]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,3.7,6,Placed,7,90.00,738963.0,221,green flag,low,Excellent
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,4.5,33,Not Placed,8,91.67,NaN,233,green flag,medium,Excellent
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,3.6,8,Placed,5,60.83,501904.0,194,Red flag,low,Average
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,2.7,5,Not Placed,8,59.17,NaN,236,Red flag,low,Excellent
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,2.1,23,Placed,9,84.17,970105.0,146,green flag,medium,Poor

In [88]:
#38. Create a placement eligibility column using apply().
def placement_eligibility(x):
    if x["total_score"]>=150 and x["attendance_pct"]>=75:
        return"Eligible"
    else:
        return"Not Eligible"
df["placement_eligibility"]=df.apply(placement_eligibility,axis=1)

In [89]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students,placement_eligibility
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,6,Placed,7,90.00,738963.0,221,green flag,low,Excellent,Eligible
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,33,Not Placed,8,91.67,NaN,233,green flag,medium,Excellent,Eligible
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,8,Placed,5,60.83,501904.0,194,Red flag,low,Average,Not Eligible
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,5,Not Placed,8,59.17,NaN,236,Red flag,low,Excellent,Not Eligible
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,23,Placed,9,84.17,970105.0,146,green flag,medium,Poor,Not Eligible

In [90]:
#39. Map placement_status values to numerical values.
num={"Placed":1,"Not Placed":0}
df["Num_Placement_Status"]=df["placement_status"].map(num)

In [91]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,placement_status,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students,placement_eligibility,Num_Placement_Status
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,Placed,7,90.00,738963.0,221,green flag,low,Excellent,Eligible,1
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,Not Placed,8,91.67,NaN,233,green flag,medium,Excellent,Eligible,0
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,Placed,5,60.83,501904.0,194,Red flag,low,Average,Not Eligible,1
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,Not Placed,8,59.17,NaN,236,Red flag,low,Excellent,Not Eligible,0
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,Placed,9,84.17,970105.0,146,green flag,medium,Poor,Not Eligible,1

In [92]:
#40. Map batch_type values to abbreviated codes.
code={"Weekday":"WD","Weekend":"WE"}
df["Batch_type_code"]=df["batch_type"].map(code)

In [93]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,feedback_score,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students,placement_eligibility,Num_Placement_Status,Batch_type_code
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,7,90.00,738963.0,221,green flag,low,Excellent,Eligible,1,WD
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,8,91.67,NaN,233,green flag,medium,Excellent,Eligible,0,WD
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,5,60.83,501904.0,194,Red flag,low,Average,Not Eligible,1,WD
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,8,59.17,NaN,236,Red flag,low,Excellent,Not Eligible,0,WE
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,9,84.17,970105.0,146,green flag,medium,Poor,Not Eligible,1,WD

In [94]:
#41. Map gender values to single-letter codes.
g={"Male":"M","Female":"F"}
df["Gender_code"]=df["gender"].map(g)

In [95]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students,placement_eligibility,Num_Placement_Status,Batch_type_code,Gender_code
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,...,90.00,738963.0,221,green flag,low,Excellent,Eligible,1,WD,M
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,...,91.67,NaN,233,green flag,medium,Excellent,Eligible,0,WD,F
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,...,60.83,501904.0,194,Red flag,low,Average,Not Eligible,1,WD,M
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,...,59.17,NaN,236,Red flag,low,Excellent,Not Eligible,0,WE,M
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,...,84.17,970105.0,146,green flag,medium,Poor,Not Eligible,1,WD,M

In [96]:
#42. Count students under each learning_intensity category.
df["learning_intensity"].value_counts()

learning_intensity
medium    291
low       209
Name: count, dtype: int64

In [99]:
#43. Calculate the percentage of placement-eligible students.
df['placement_eligibility'].value_counts(normalize=True)['Eligible'] * 100

np.float64(46.800000000000004)

In [113]:
#44. Identify the city with the highest number of placed students.
df[df["placement_status"] == "laced"]["city"].value_counts().idxmax()

ValueError: attempt to get argmax of an empty sequence

In [106]:
#45. Compare average total_score for placed and not placed students.
p=(df["placement_status"]=="Placed").sum()
np=(df["placement_status"]=="Not Placed").sum()
total_score=p-np
print(total_score)

166

In [107]:
#46. Identify the top 5 students based on total_score.
df.sort_values(by='total_score', ascending=False).head(5)

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,...,attendance_pct,salary_offered,total_score,attendance_flag,learning_intensity,Classify_students,placement_eligibility,Num_Placement_Status,Batch_type_code,Gender_code
475,1476,Student_476,Female,Chennai,2024-02-05,Data Analytics,Weekday,120,97,99,...,80.83,855839.0,292,green flag,medium,Excellent,Eligible,1,WD,F
178,1179,Student_179,Male,Mumbai,2024-04-22,AI & ML,Weekday,120,82,99,...,68.33,NaN,284,Red flag,medium,Excellent,Not Eligible,0,WD,M
183,1184,Student_184,Male,Mumbai,2024-05-21,Data Science,Weekend,120,112,94,...,93.33,728556.0,279,green flag,low,Excellent,Eligible,1,WE,M
263,1264,Student_264,Male,Delhi,2024-05-13,Generative AI,Weekday,120,101,97,...,84.17,301515.0,278,green flag,low,Excellent,Eligible,1,WD,M
485,1486,Student_486,Female,Mumbai,2024-04-28,AI & ML,Weekday,120,62,97,...,51.67,716704.0,278,Red flag,medium,Excellent,Not Eligible,1,WD,F