In [1]:
import pandas as pd

In [134]:
df=pd.read_csv("Downloads/edtech_student_learning_data.csv")

In [135]:
df.head()

,student_id,student_name,gender,city,enrollment_date,course,batch_type,total_sessions,sessions_attended,avg_quiz_score,assignment_score,project_score,final_rating,learning_hours,placement_status,feedback_score,attendance_pct,salary_offered
0,1001,Student_1,Male,Hyderabad,2024-11-25,Generative AI,Weekday,120,108,59,96,66,3.7,6,Placed,7,90.00,738963.0
1,1002,Student_2,Female,Hyderabad,2024-09-29,AI & ML,Weekday,120,110,57,93,83,4.5,33,Not Placed,8,91.67,NaN
2,1003,Student_3,Male,Pune,2024-12-05,Data Science,Weekday,120,73,49,72,73,3.6,8,Placed,5,60.83,501904.0
3,1004,Student_4,Male,Delhi,2024-03-09,AI & ML,Weekend,120,71,64,91,81,2.7,5,Not Placed,8,59.17,NaN
4,1005,Student_5,Male,Mumbai,2024-02-03,Generative AI,Weekday,120,101,41,55,50,2.1,23,Placed,9,84.17,970105.0

In [45]:
df.dtypes

student_id             int64
student_name          object
gender                object
city                  object
enrollment_date       object
course                object
batch_type            object
total_sessions         int64
sessions_attended      int64
avg_quiz_score         int64
assignment_score       int64
project_score          int64
final_rating         float64
learning_hours         int64
placement_status      object
feedback_score         int64
attendance_pct       float64
salary_offered       float64
total_score            int64
placed                  bool
dtype: object

In [7]:
#1. Group the data by course and calculate the average attendance percentage.
df.groupby("course")["attendance_pct"].mean()

course
AI & ML           72.983095
Data Analytics    73.146713
Data Science      73.632578
Generative AI     74.035648
Name: attendance_pct, dtype: float64

In [8]:
#2. Group the data by city and count the number of students in each city.
df.groupby("city")["student_id"].count()

city
Bangalore     82
Chennai       73
Delhi         68
Hyderabad    100
Mumbai        95
Pune          87
Name: student_id, dtype: int64

In [9]:
#3. Group the data by batch_type and calculate the average quiz score.
df.groupby("batch_type")["avg_quiz_score"].mean()

batch_type
Weekday    69.628099
Weekend    69.577947
Name: avg_quiz_score, dtype: float64

In [12]:
#4. Group the data by placement_status and calculate the average total_score.
df["total_score"]=df["avg_quiz_score"]+df["assignment_score"]+df["project_score"]
df.groupby("placement_status")["total_score"].mean()

placement_status
Not Placed    215.307692
Placed        217.660714
Name: total_score, dtype: float64

In [13]:
#5. Group the data by course and city and calculate the number of students in each combination
df.groupby(["course","city"])["student_id"].count()

course          city
AI & ML         Bangalore    21
                Chennai      14
                Delhi        16
                Hyderabad    19
                Mumbai       30
                Pune         26
Data Analytics  Bangalore    25
                Chennai      18
                Delhi        21
                Hyderabad    33
                Mumbai       26
                Pune         20
Data Science    Bangalore    19
                Chennai      24
                Delhi        12
                Hyderabad    31
                Mumbai       20
                Pune         22
Generative AI   Bangalore    17
                Chennai      17
                Delhi        19
                Hyderabad    17
                Mumbai       19
                Pune         19
Name: student_id, dtype: int64

In [14]:
#6. Group the data by course and calculate the maximum, minimum, and average project score.
df.groupby("course")["project_score"].agg(["max","min","mean"])

                max  min       mean
course
AI & ML          99   50  74.158730
Data Analytics   99   50  75.839161
Data Science     99   50  75.992188
Generative AI    98   50  75.037037

In [15]:
#7. Group the data by city and calculate total and average learning hours.
df.groupby("city")["learning_hours"].agg(["sum","mean"])

            sum       mean
city
Bangalore  1870  22.804878
Chennai    1557  21.328767
Delhi      1506  22.147059
Hyderabad  2206  22.060000
Mumbai     2150  22.631579
Pune       1886  21.678161

In [16]:
#8. Group the data by course and placement_status and count students.
df.groupby(["course","placement_status"])["student_id"].count()

course          placement_status
AI & ML         Not Placed          48
                Placed              78
Data Analytics  Not Placed          44
                Placed              99
Data Science    Not Placed          40
                Placed              88
Generative AI   Not Placed          37
                Placed              71
Name: student_id, dtype: int64

In [23]:
#9. Filter grouped results to display only courses with average attendance percentage greater than 80.
avg_attendance_pct=df.groupby("course")["attendance_pct"].mean()
avg_attendance_pct.head()

course
AI & ML           72.983095
Data Analytics    73.146713
Data Science      73.632578
Generative AI     74.035648
Name: attendance_pct, dtype: float64

In [24]:
avg_attendance_pct[avg_attendance_pct > 80]

Series([], Name: attendance_pct, dtype: float64)

In [25]:
#10. Filter grouped results to show only cities with more than 50 students.
no_student=df.groupby("city")["student_id"].count()
no_student.head()

city
Bangalore     82
Chennai       73
Delhi         68
Hyderabad    100
Mumbai        95
Name: student_id, dtype: int64

In [26]:
no_student[no_student >50]

city
Bangalore     82
Chennai       73
Delhi         68
Hyderabad    100
Mumbai        95
Pune          87
Name: student_id, dtype: int64

In [28]:
#11. Perform multiple aggregations on course to calculate average quiz score, average assignment score, and average project score.
df.groupby("course").agg(avg_quiz=("avg_quiz_score","mean"),
                         avg_assign_score=("assignment_score","mean"),
                         avg_project_score=("project_score","mean"))

                 avg_quiz  avg_assign_score  avg_project_score
course
AI & ML         69.023810         71.642857          74.158730
Data Analytics  69.041958         71.545455          75.839161
Data Science    69.960938         72.656250          75.992188
Generative AI   70.592593         72.166667          75.037037

In [31]:
#12. Perform named aggregations on course to calculate average_attendance, max_project_score, and mean_total_score.
df.groupby("course").agg(average_attendance=("attendance_pct","mean"),
                         max_project_score=("project_score","max"),
                         mean_total_score=("total_score","mean"))

                average_attendance  max_project_score  mean_total_score
course
AI & ML                  72.983095                 99        214.825397
Data Analytics           73.146713                 99        216.426573
Data Science             73.632578                 99        218.609375
Generative AI            74.035648                 98        217.796296

In [136]:
#13. Perform named aggregations on city to calculate total_students, placed_students, and average_salary.
df["place"]=df["placement_status"]=="Placed"
df.groupby("city").agg(total_students=("student_id","count"),
                       placed_students=("place","sum"),
                       average_salary=("salary_offered","mean"))

           total_students  placed_students  average_salary
city
Bangalore              82               62   805241.500000
Chennai                73               44   823148.090909
Delhi                  68               37   759655.918919
Hyderabad             100               69   703994.405797
Mumbai                 95               64   767943.218750
Pune                   87               60   779828.883333

In [137]:
df["place"].sum()

np.int64(336)

In [139]:
#14. Extract year from enrollment_date and add it as a new column.
df["enrollment_date"] = pd.to_datetime(df["enrollment_date"])
df["year"]=df["enrollment_date"].dt.year

In [140]:
df["year"]

0      2024
1      2024
2      2024
3      2024
4      2024
       ...
500    2024
501    2024
502    2024
503    2024
504    2024
Name: year, Length: 505, dtype: int32

In [141]:
#15. Extract month number from enrollment_date and add it as a new column.
df["month"]=df["enrollment_date"].dt.month

In [60]:
df["month"]

0      11
1       9
2      12
3       3
4       2
       ..
500     3
501    10
502     4
503     1
504     5
Name: month, Length: 505, dtype: int32

In [142]:
#16. Extract month name from enrollment_date and add it as a new column.
df["month_name"]=df["enrollment_date"].dt.month_name()

In [62]:
df["month_name"]

0       November
1      September
2       December
3          March
4       February
         ...
500        March
501      October
502        April
503      January
504          May
Name: month_name, Length: 505, dtype: object

In [143]:
#17. Extract day name from enrollment_date and add it as a new column.
df["day_name"]=df["enrollment_date"].dt.day_name()

In [64]:
df["day_name"]

0        Monday
1        Sunday
2      Thursday
3      Saturday
4      Saturday
         ...
500    Thursday
501     Tuesday
502    Thursday
503    Saturday
504      Monday
Name: day_name, Length: 505, dtype: object

In [144]:
#18. Extract quarter from enrollment_date and add it as a new column.
df["quarter"]=df["enrollment_date"].dt.quarter

In [67]:
df["quarter"]

0      4
1      3
2      4
3      1
4      1
      ..
500    1
501    4
502    2
503    1
504    2
Name: quarter, Length: 505, dtype: int32

In [145]:
#19. Group the data by year and calculate the number of student enrollments.
df.groupby("year")["student_id"].count()

year
2024    505
Name: student_id, dtype: int64

In [146]:
#20. Group the data by month name and calculate average attendance percentage.
df.groupby("month_name")["attendance_pct"].mean()

month_name
April        71.224490
August       69.603333
December     73.603243
February     71.824054
January      72.783200
July         76.972667
June         72.479268
March        72.562500
May          74.296889
November     73.775714
October      78.541731
September    73.257273
Name: attendance_pct, dtype: float64

In [70]:
#21. Group the data by quarter and calculate average total_score.
df.groupby("quarter")["total_score"].mean()

quarter
1    214.708661
2    217.933333
3    217.533333
4    217.326087
Name: total_score, dtype: float64

In [71]:
#22. Group the data by day name and count the number of enrollments.
df.groupby("day_name")["enrollment_date"].count()

day_name
Friday       74
Monday       79
Saturday     86
Sunday       74
Thursday     78
Tuesday      61
Wednesday    53
Name: enrollment_date, dtype: int64

In [76]:
#23. Identify the month with the highest number of enrollments.
df.groupby("month_name")["enrollment_date"].count().idxmax()

'October'

In [79]:
#24. Identify the quarter with the highest average project score.
df.groupby("quarter")["project_score"].mean().idxmax()

np.int32(2)

In [80]:
#25. Group the data by year and course and calculate average quiz score.
df.groupby(["year","course"])["avg_quiz_score"].mean()

year  course
2024  AI & ML           69.023810
      Data Analytics    69.041958
      Data Science      69.960938
      Generative AI     70.592593
Name: avg_quiz_score, dtype: float64

In [147]:
#26. Group the data by month name and placement_status and count students.
df.groupby(["month_name","placement_status"])["student_id"].count()

month_name  placement_status
April       Not Placed          15
            Placed              34
August      Not Placed          16
            Placed              26
December    Not Placed          16
            Placed              21
February    Not Placed          10
            Placed              27
January     Not Placed          19
            Placed              31
July        Not Placed          10
            Placed              20
June        Not Placed          14
            Placed              27
March       Not Placed          13
            Placed              27
May         Not Placed          13
            Placed              32
November    Not Placed          18
            Placed              31
October     Not Placed          17
            Placed              35
September   Not Placed           8
            Placed              25
Name: student_id, dtype: int64

In [149]:
#27. Group the data by city and year and calculate placement count.
df.groupby(["city","year"])["placement_status"].count()

city       year
Bangalore  2024     82
Chennai    2024     73
Delhi      2024     68
Hyderabad  2024    100
Mumbai     2024     95
Pune       2024     87
Name: placement_status, dtype: int64

In [104]:
#28. Filter grouped year-wise enrollments to display only years with more than 100 enrollments.
year_enroll=df.groupby("year").size()
year_enroll[year_enroll>100].index

Index([2024], dtype='int32', name='year')

In [105]:
#29. Filter grouped course-wise performance to show only courses with average total_score above 220.
course_wise=df.groupby("course")["total_score"].mean()
course_wise[course_wise>220].index

Index([], dtype='object', name='course')

In [108]:
#30. Compare average attendance percentage across quarters.
df.groupby("quarter")["attendance_pct"].mean()

quarter
1    72.434252
2    72.629704
3    72.857238
4    75.525362
Name: attendance_pct, dtype: float64

In [109]:
#31. Calculate average salary offered per course using groupby.
df.groupby("course")["salary_offered"].mean()

course
AI & ML           785484.230769
Data Analytics    788028.545455
Data Science      781899.318182
Generative AI     713728.661972
Name: salary_offered, dtype: float64

In [110]:
#32. Calculate average salary offered per city using groupby
df.groupby("city")["salary_offered"].mean()

city
Bangalore    805241.500000
Chennai      823148.090909
Delhi        759655.918919
Hyderabad    703994.405797
Mumbai       767943.218750
Pune         779828.883333
Name: salary_offered, dtype: float64

In [113]:
#33. Identify top 3 cities based on average salary offered.
df.groupby("city")["salary_offered"].mean().sort_values(ascending=False).head(3)

city
Chennai      823148.090909
Bangalore    805241.500000
Pune         779828.883333
Name: salary_offered, dtype: float64

In [153]:
#34. Identify the course with the highest placement rate using groupby analysis
df.groupby("course")["place"].sum().sort_values(ascending=False).head(1)

course
Data Analytics    99
Name: place, dtype: int64

In [154]:
#35. Group the data by batch_type and quarter to analyze attendance patterns.
df.groupby(["batch_type","quarter"])["attendance_pct"].mean()

batch_type  quarter
Weekday     1          71.610000
            2          71.702286
            3          74.947917
            4          73.756308
Weekend     1          73.149412
            2          73.628462
            3          71.096667
            4          77.100548
Name: attendance_pct, dtype: float64

In [163]:
#36. Group the data by month name and course to analyze enrollment distribution.
df.groupby(["month_name","course"])["enrollment_date"].count()

month_name  course
April       AI & ML            7
            Data Analytics    17
            Data Science      13
            Generative AI     12
August      AI & ML           12
            Data Analytics    15
            Data Science       6
            Generative AI      9
December    AI & ML            9
            Data Analytics    11
            Data Science      11
            Generative AI      6
February    AI & ML           10
            Data Analytics    10
            Data Science      11
            Generative AI      6
January     AI & ML           14
            Data Analytics    15
            Data Science      11
            Generative AI     10
July        AI & ML           10
            Data Analytics     5
            Data Science       8
            Generative AI      7
June        AI & ML            8
            Data Analytics    13
            Data Science      13
            Generative AI      7
March       AI & ML           13
            Data Analytics    11
            Data Science       5
            Generative AI     11
May         AI & ML            8
            Data Analytics    12
            Data Science      15
            Generative AI     10
November    AI & ML           15
            Data Analytics    10
            Data Science      11
            Generative AI     13
October     AI & ML           14
            Data Analytics    11
            Data Science      17
            Generative AI     10
September   AI & ML            6
            Data Analytics    13
            Data Science       7
            Generative AI      7
Name: enrollment_date, dtype: int64

In [179]:
#37. Identify days of the week with maximum enrollments.
max_enroll=df["day_name"].value_counts()
(max_enroll.idxmax(),max_enroll.max())

('Saturday', 86)

In [181]:
#38. Analyze placement status distribution across quarters.
df.groupby("quarter")["placement_status"].count()

quarter
1    127
2    135
3    105
4    138
Name: placement_status, dtype: int64