In [1]:
import pandas as pd

In [2]:
#1. Load the Amazon Prime dataset into a Pandas DataFrame.
df=pd.read_csv("Downloads/amazon_prime_video_data.csv")

In [3]:
df.head()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00

In [4]:
#2. Display the first 10 records of the dataset.
df.head(10)

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00
5,5006,Movie,Drama,Hindi,2010,104,6.2,A,Australia,2022-12-27,96.06,51.0,6.42,Basic,No,0.84
6,5007,Movie,Action,Kannada,2019,121,6.9,A,USA,2021-03-27,111.84,130.0,6.66,Premium,No,6.47
7,5008,Movie,Sci-Fi,Telugu,2020,65,5.9,A,Canada,2023-02-24,90.44,68.0,8.43,Premium,No,45.42
8,5009,Movie,Comedy,English,2005,65,6.8,U,USA,2023-07-22,105.41,67.0,1.97,Standard,No,32.48
9,5010,Movie,Thriller,Kannada,2017,107,7.0,U,Canada,2022-05-02,54.07,80.0,8.24,Mobile,No,4.94

In [5]:
#3. Display the last 5 records of the dataset.
df.tail()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
601,5510,Movie,Action,Malayalam,2015,169,7.8,A,Australia,2023-07-15,91.25,31.0,8.26,Basic,No,35.79
602,5349,Movie,Action,Telugu,2018,119,4.9,A,UK,2021-03-02,110.01,NaN,0.41,Premium,Yes,1.58
603,5339,Movie,Action,Malayalam,2009,97,6.7,A,Australia,2023-11-29,60.76,129.0,7.76,Standard,Yes,47.08
604,5434,Movie,Romance,Telugu,2013,162,9.3,U/A,UK,2023-09-30,46.04,33.0,5.50,Basic,Yes,23.48
605,5491,TV Show,Romance,English,2020,140,6.0,U,Australia,2022-05-29,37.05,122.0,12.68,Basic,No,27.18

In [6]:
#4. Check the total number of rows and columns.
df.shape

(606, 16)

In [7]:
#5. Display all column names with their data types.
df.dtypes

content_id              int64
content_type           object
genre                  object
language               object
release_year            int64
duration_minutes        int64
imdb_rating           float64
age_rating             object
country                object
added_date             object
views_millions        float64
avg_watch_time_min    float64
likes_millions        float64
subscription_plan      object
is_trending            object
revenue_millions      float64
dtype: object

In [8]:
#6. Generate summary statistics for numerical columns.
df.describe()

,content_id,release_year,duration_minutes,imdb_rating,views_millions,avg_watch_time_min,likes_millions,revenue_millions
count,606.000000,606.000000,606.000000,566.000000,606.000000,570.000000,606.000000,606.000000
mean,5301.823432,2014.714521,119.330033,6.916961,61.660677,86.482456,7.474241,25.315792
std,173.127136,5.712624,34.121949,1.447780,33.650763,41.767713,4.332711,13.654265
min,5001.000000,2005.000000,60.000000,4.500000,0.150000,20.000000,0.010000,0.140000
25%,5152.250000,2010.000000,91.250000,5.600000,32.880000,48.250000,3.910000,13.952500
50%,5303.500000,2015.000000,120.000000,6.900000,61.415000,85.000000,7.430000,25.350000
75%,5451.750000,2020.000000,147.000000,8.100000,91.452500,124.750000,11.290000,37.097500
max,5600.000000,2024.000000,179.000000,9.500000,119.880000,159.000000,15.000000,49.810000

In [9]:
#7. Identify columns containing missing values.
df.isna()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
602,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
603,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
604,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
605,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
#8. Count missing values in each column.
df.isna().sum()

content_id             0
content_type           0
genre                  0
language               0
release_year           0
duration_minutes       0
imdb_rating           40
age_rating             0
country                0
added_date             0
views_millions         0
avg_watch_time_min    36
likes_millions         0
subscription_plan      0
is_trending            0
revenue_millions       0
dtype: int64

In [11]:
#9. Calculate the percentage of missing values in imdb_rating
df["imdb_rating"].isna().mean()*100

np.float64(6.6006600660066)

In [12]:
#10. Fill missing imdb_rating values using the mean.
df['imdb_rating'].fillna(df['imdb_rating'].mean())

0      6.916961
1      7.300000
2      9.500000
3      4.600000
4      8.100000
         ...
601    7.800000
602    4.900000
603    6.700000
604    9.300000
605    6.000000
Name: imdb_rating, Length: 606, dtype: float64

In [13]:
#11. Fill missing avg_watch_time_min values using the median.
df["avg_watch_time_min"]=df["avg_watch_time_min"].fillna(df["avg_watch_time_min"].median())
df["avg_watch_time_min"]

0       50.0
1      127.0
2       74.0
3      132.0
4      103.0
       ...
601     31.0
602     85.0
603    129.0
604     33.0
605    122.0
Name: avg_watch_time_min, Length: 606, dtype: float64

In [14]:
#12. Verify that missing values are handled.
df.isna().sum()

content_id             0
content_type           0
genre                  0
language               0
release_year           0
duration_minutes       0
imdb_rating           40
age_rating             0
country                0
added_date             0
views_millions         0
avg_watch_time_min     0
likes_millions         0
subscription_plan      0
is_trending            0
revenue_millions       0
dtype: int64

In [15]:
#13. Check if duplicate records exist.
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
601     True
602     True
603     True
604     True
605     True
Length: 606, dtype: bool

In [16]:
#14. Count total duplicate rows.
df.duplicated().sum()

np.int64(6)

In [17]:
#15. Display duplicate records.
df[df.duplicated()]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
600,5482,TV Show,Thriller,English,2009,60,5.6,U,India,2021-03-15,113.20,128.0,13.96,Standard,No,20.35
601,5510,Movie,Action,Malayalam,2015,169,7.8,A,Australia,2023-07-15,91.25,31.0,8.26,Basic,No,35.79
602,5349,Movie,Action,Telugu,2018,119,4.9,A,UK,2021-03-02,110.01,85.0,0.41,Premium,Yes,1.58
603,5339,Movie,Action,Malayalam,2009,97,6.7,A,Australia,2023-11-29,60.76,129.0,7.76,Standard,Yes,47.08
604,5434,Movie,Romance,Telugu,2013,162,9.3,U/A,UK,2023-09-30,46.04,33.0,5.50,Basic,Yes,23.48
605,5491,TV Show,Romance,English,2020,140,6.0,U,Australia,2022-05-29,37.05,122.0,12.68,Basic,No,27.18

In [18]:
#16. Remove duplicate rows permanently.
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
595    False
596    False
597    False
598    False
599    False
Length: 600, dtype: bool

In [20]:
#17. Verify the dataset shape after removing duplicates.
df.shape

(600, 16)

In [21]:
#18. Find the number of unique values in content_type.
df["content_type"].nunique()

2

In [22]:
#19. Find the number of unique values in genre.
df["genre"].nunique()

7

In [23]:
#20. Display all unique languages.
df["language"].unique()

array(['Tamil', 'Malayalam', 'Telugu', 'Hindi', 'Kannada', 'English'],
      dtype=object)

In [24]:
#21. Count content by genre.
df["genre"].count()

np.int64(600)

In [25]:
#22. Count content by language.
df["language"].count()

np.int64(600)

In [26]:
#23. Filter content with imdb_rating greater than 8.
df[df["imdb_rating"]>8]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00
10,5011,TV Show,Drama,Malayalam,2014,154,9.1,U/A,Australia,2022-12-21,69.92,100.0,10.39,Basic,No,40.35
11,5012,TV Show,Drama,English,2014,60,8.9,U,Australia,2022-10-17,18.52,125.0,14.99,Premium,Yes,45.34
12,5013,Movie,Sci-Fi,Malayalam,2011,70,9.2,U/A,Australia,2023-09-09,106.86,157.0,7.51,Standard,No,6.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,5589,TV Show,Documentary,English,2013,98,9.3,U/A,UK,2021-05-13,37.06,21.0,5.63,Premium,No,17.69
589,5590,TV Show,Drama,Malayalam,2012,166,8.3,U/A,USA,2023-07-21,85.92,117.0,1.64,Standard,No,8.20
592,5593,Movie,Documentary,Tamil,2009,143,8.9,U,USA,2023-10-16,37.18,144.0,4.34,Standard,Yes,20.72
594,5595,TV Show,Sci-Fi,Telugu,2017,170,8.4,A,Australia,2021-07-29,1.85,24.0,1.22,Premium,No,15.48
595,5596,TV Show,Action,Tamil,2024,81,8.1,U/A,UK,2023-06-24,90.33,155.0,0.73,Premium,Yes,23.98

In [27]:
#24. Filter content with views_millions greater than 50.
df[df["views_millions"]>50]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00
5,5006,Movie,Drama,Hindi,2010,104,6.2,A,Australia,2022-12-27,96.06,51.0,6.42,Basic,No,0.84
6,5007,Movie,Action,Kannada,2019,121,6.9,A,USA,2021-03-27,111.84,130.0,6.66,Premium,No,6.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,5592,Movie,Sci-Fi,English,2005,140,NaN,U/A,India,2022-08-11,62.32,126.0,2.26,Mobile,No,22.00
593,5594,Movie,Romance,Malayalam,2009,130,5.0,U,India,2023-08-08,50.32,135.0,9.25,Basic,Yes,42.95
595,5596,TV Show,Action,Tamil,2024,81,8.1,U/A,UK,2023-06-24,90.33,155.0,0.73,Premium,Yes,23.98
596,5597,Movie,Sci-Fi,Hindi,2017,87,6.4,U,Canada,2023-03-17,61.81,59.0,11.29,Standard,No,47.16
599,5600,Movie,Comedy,English,2024,100,4.5,U/A,Canada,2022-03-26,70.64,90.0,8.03,Basic,No,41.49

In [28]:
#25. Filter content released after 2018.
df[df["release_year"]<2018]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68
5,5006,Movie,Drama,Hindi,2010,104,6.2,A,Australia,2022-12-27,96.06,51.0,6.42,Basic,No,0.84
8,5009,Movie,Comedy,English,2005,65,6.8,U,USA,2023-07-22,105.41,67.0,1.97,Standard,No,32.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592,5593,Movie,Documentary,Tamil,2009,143,8.9,U,USA,2023-10-16,37.18,144.0,4.34,Standard,Yes,20.72
593,5594,Movie,Romance,Malayalam,2009,130,5.0,U,India,2023-08-08,50.32,135.0,9.25,Basic,Yes,42.95
594,5595,TV Show,Sci-Fi,Telugu,2017,170,8.4,A,Australia,2021-07-29,1.85,24.0,1.22,Premium,No,15.48
596,5597,Movie,Sci-Fi,Hindi,2017,87,6.4,U,Canada,2023-03-17,61.81,59.0,11.29,Standard,No,47.16
598,5599,Movie,Drama,Malayalam,2008,104,5.3,A,UK,2023-11-28,47.41,81.0,5.88,Mobile,No,36.17

In [29]:
#26. Filter content belonging to Action or Thriller genre.
df[df['genre'].isin(['Action','Thriller'])]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70
6,5007,Movie,Action,Kannada,2019,121,6.9,A,USA,2021-03-27,111.84,130.0,6.66,Premium,No,6.47
9,5010,Movie,Thriller,Kannada,2017,107,7.0,U,Canada,2022-05-02,54.07,80.0,8.24,Mobile,No,4.94
15,5016,TV Show,Action,Telugu,2016,90,8.4,U/A,USA,2021-06-06,60.29,85.0,13.41,Standard,No,21.69
16,5017,Movie,Action,Kannada,2015,178,9.0,U,USA,2021-07-27,93.79,100.0,10.88,Mobile,No,32.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,5585,Movie,Thriller,Hindi,2015,131,6.8,U,Australia,2022-03-21,56.87,61.0,4.50,Standard,No,43.26
585,5586,TV Show,Action,Hindi,2009,78,NaN,A,USA,2024-04-01,66.58,25.0,9.23,Premium,No,3.80
590,5591,Movie,Action,Tamil,2019,108,8.0,U/A,UK,2024-02-22,14.90,101.0,7.97,Mobile,No,13.46
595,5596,TV Show,Action,Tamil,2024,81,8.1,U/A,UK,2023-06-24,90.33,155.0,0.73,Premium,Yes,23.98
597,5598,Movie,Thriller,Telugu,2021,174,NaN,A,Canada,2024-02-28,24.43,41.0,13.16,Standard,No,19.62

In [30]:
#27. Filter content available in Hindi or English.
df[df["language"].isin(["Hindi","English"])]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
5,5006,Movie,Drama,Hindi,2010,104,6.2,A,Australia,2022-12-27,96.06,51.0,6.42,Basic,No,0.84
8,5009,Movie,Comedy,English,2005,65,6.8,U,USA,2023-07-22,105.41,67.0,1.97,Standard,No,32.48
11,5012,TV Show,Drama,English,2014,60,8.9,U,Australia,2022-10-17,18.52,125.0,14.99,Premium,Yes,45.34
19,5020,Movie,Drama,English,2017,118,7.4,U,USA,2022-05-10,61.69,85.0,4.45,Standard,Yes,19.78
20,5021,TV Show,Action,English,2015,67,5.5,U,Canada,2022-02-23,96.68,66.0,1.43,Standard,No,30.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,5587,Movie,Documentary,Hindi,2011,125,4.8,U,UK,2021-12-28,102.04,53.0,7.80,Premium,No,20.87
588,5589,TV Show,Documentary,English,2013,98,9.3,U/A,UK,2021-05-13,37.06,21.0,5.63,Premium,No,17.69
591,5592,Movie,Sci-Fi,English,2005,140,NaN,U/A,India,2022-08-11,62.32,126.0,2.26,Mobile,No,22.00
596,5597,Movie,Sci-Fi,Hindi,2017,87,6.4,U,Canada,2023-03-17,61.81,59.0,11.29,Standard,No,47.16
599,5600,Movie,Comedy,English,2024,100,4.5,U/A,Canada,2022-03-26,70.64,90.0,8.03,Basic,No,41.49

In [31]:
#28. Filter content with duration between 90 and 150 minutes.
df[df["duration_minutes"].between(90,150)]

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92
5,5006,Movie,Drama,Hindi,2010,104,6.2,A,Australia,2022-12-27,96.06,51.0,6.42,Basic,No,0.84
6,5007,Movie,Action,Kannada,2019,121,6.9,A,USA,2021-03-27,111.84,130.0,6.66,Premium,No,6.47
9,5010,Movie,Thriller,Kannada,2017,107,7.0,U,Canada,2022-05-02,54.07,80.0,8.24,Mobile,No,4.94
13,5014,Movie,Sci-Fi,Kannada,2020,146,9.3,A,India,2023-05-30,79.39,113.0,14.34,Premium,No,26.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,5592,Movie,Sci-Fi,English,2005,140,NaN,U/A,India,2022-08-11,62.32,126.0,2.26,Mobile,No,22.00
592,5593,Movie,Documentary,Tamil,2009,143,8.9,U,USA,2023-10-16,37.18,144.0,4.34,Standard,Yes,20.72
593,5594,Movie,Romance,Malayalam,2009,130,5.0,U,India,2023-08-08,50.32,135.0,9.25,Basic,Yes,42.95
598,5599,Movie,Drama,Malayalam,2008,104,5.3,A,UK,2023-11-28,47.41,81.0,5.88,Mobile,No,36.17
599,5600,Movie,Comedy,English,2024,100,4.5,U/A,Canada,2022-03-26,70.64,90.0,8.03,Basic,No,41.49

In [32]:
#29. Create a new column popularity_score as views_millions + likes_millions.
df["popularity_score"]=df["views_millions"]+df["likes_millions"]
df.head()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions,popularity_score
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82,87.24
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70,6.15
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92,22.39
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68,89.28
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00,57.60

In [33]:
#30. Create a new column rating_category using apply().
def example(x):
    if x >=8:
        return "High"
    elif x>=5:
        return "Medium"
    else:
        return "Low"
df["rating_category"]=df["imdb_rating"].apply(example)
df.head()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions,popularity_score,rating_category
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82,87.24,Low
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70,6.15,Medium
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92,22.39,High
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68,89.28,Low
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00,57.60,High

In [34]:
#31. Map subscription_plan to short codes.
code={"Basic":"B","Standard":"S","Mobile":"M","Premium":"P"}
df["subscription_plan_code"]=df["subscription_plan"].map(code)

In [35]:
df.head()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions,popularity_score,rating_category,subscription_plan_code
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82,87.24,Low,B
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70,6.15,Medium,S
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92,22.39,High,M
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68,89.28,Low,B
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00,57.60,High,B

In [36]:
#32. Map is_trending values to numerical format.
code={"No":0,"Yes":1}
df["is_trending_code"]=df["is_trending"].map(code)

In [37]:
df.head()

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions,popularity_score,rating_category,subscription_plan_code,is_trending_code
0,5001,Movie,Romance,Tamil,2014,80,NaN,U,Australia,2022-08-21,87.23,50.0,0.01,Basic,No,9.82,87.24,Low,B,0
1,5002,TV Show,Action,Malayalam,2010,165,7.3,U/A,Canada,2023-03-23,0.63,127.0,5.52,Standard,No,36.70,6.15,Medium,S,0
2,5003,Movie,Documentary,Malayalam,2024,129,9.5,A,UK,2023-10-05,13.78,74.0,8.61,Mobile,No,3.92,22.39,High,M,0
3,5004,TV Show,Comedy,Telugu,2016,169,4.6,U/A,India,2023-09-04,86.49,132.0,2.79,Basic,No,6.68,89.28,Low,B,0
4,5005,TV Show,Documentary,Malayalam,2021,157,8.1,U/A,Australia,2024-01-05,53.47,103.0,4.13,Basic,No,30.00,57.60,High,B,0

In [38]:
#33. Count content by subscription_plan.
df["subscription_plan"].count()

np.int64(600)

In [39]:
#34. Identify top 5 contents based on popularity_score.
df.sort_values("popularity_score",ascending=False).head(5)

,content_id,content_type,genre,language,release_year,duration_minutes,imdb_rating,age_rating,country,added_date,views_millions,avg_watch_time_min,likes_millions,subscription_plan,is_trending,revenue_millions,popularity_score,rating_category,subscription_plan_code,is_trending_code
403,5404,Movie,Romance,Malayalam,2015,117,4.6,A,Canada,2023-07-22,118.36,48.0,14.22,Premium,Yes,37.47,132.58,Low,P,1
299,5300,TV Show,Sci-Fi,Tamil,2014,129,8.1,U,Australia,2021-06-02,119.88,48.0,12.47,Mobile,No,39.44,132.35,High,M,0
521,5522,Movie,Comedy,Hindi,2012,67,7.2,U,Australia,2023-08-27,119.04,152.0,13.03,Mobile,No,29.25,132.07,Medium,M,0
572,5573,TV Show,Action,English,2012,90,8.2,U/A,Australia,2022-10-09,115.36,135.0,14.69,Standard,No,11.58,130.05,High,S,0
210,5211,TV Show,Comedy,Malayalam,2015,74,7.1,U,UK,2023-04-10,116.14,85.0,13.89,Basic,No,27.49,130.03,Medium,B,0

In [40]:
#35. Group the data by content_type and count total content.
df.groupby("content_type")["content_type"].count()

content_type
Movie      367
TV Show    233
Name: content_type, dtype: int64

In [41]:
#36. Group the data by genre and calculate average imdb_rating.
df.groupby("genre")["imdb_rating"].mean()

genre
Action         7.018987
Comedy         6.967164
Documentary    6.674737
Drama          7.084783
Romance        6.798529
Sci-Fi         7.201111
Thriller       6.624638
Name: imdb_rating, dtype: float64

In [42]:
#37. Group the data by language and calculate average views_millions
df.groupby("language")["views_millions"].mean()

language
English      64.021650
Hindi        63.005385
Kannada      61.063214
Malayalam    59.209717
Tamil        63.118468
Telugu       58.147609
Name: views_millions, dtype: float64

In [43]:
#38. Group the data by subscription_plan and calculate average revenue
df.groupby("subscription_plan")["revenue_millions"].mean()

subscription_plan
Basic       25.284831
Mobile      25.812690
Premium     24.575912
Standard    25.539071
Name: revenue_millions, dtype: float64

In [44]:
#39. Group the data by country and count content.
df.groupby("country")["country"].count()

country
Australia    134
Canada       120
India        121
UK           124
USA          101
Name: country, dtype: int64

In [45]:
#40. Group the data by genre and calculate total revenue.
df.groupby("genre")["revenue_millions"].sum()

genre
Action         2127.80
Comedy         1928.84
Documentary    2379.68
Drama          2503.21
Romance        1933.78
Sci-Fi         2498.81
Thriller       1813.79
Name: revenue_millions, dtype: float64

In [46]:
#41. Group the data by content_type and calculate average duration.
df.groupby("content_type")["duration_minutes"].mean()

content_type
Movie      118.948229
TV Show    119.798283
Name: duration_minutes, dtype: float64

In [47]:
#42. Group the data by is_trending and calculate average views.
df.groupby("is_trending")["views_millions"].mean()

is_trending
No     63.072095
Yes    58.372613
Name: views_millions, dtype: float64

In [48]:
#43. Filter grouped genres having average imdb_rating greater than 7.5.
df[df["imdb_rating"]>7.5].groupby("genre")["imdb_rating"].mean()

genre
Action         8.361765
Comedy         8.590476
Documentary    8.377419
Drama          8.671053
Romance        8.566667
Sci-Fi         8.402326
Thriller       8.386364
Name: imdb_rating, dtype: float64

In [49]:
#44. Filter grouped languages having more than 50 contents.
content=df["language"].value_counts()
content[content>50]

language
Tamil        111
Malayalam    106
Hindi        104
English      103
Telugu        92
Kannada       84
Name: count, dtype: int64

In [50]:
#45. Perform multiple aggregations on genre for views, likes, and revenue.
df.groupby("genre").agg({"views_millions":["mean","max","min","sum","count"],
                         "likes_millions":["mean","max","min","sum","count"],
                         "revenue_millions":["mean","max","min","sum","count"]})

            views_millions                              likes_millions         \
                      mean     max   min      sum count           mean    max
genre
Action           62.880575  118.81  0.63  5470.61    87       7.316897  15.00
Comedy           54.443750  119.04  0.97  3919.95    72       7.429167  14.51
Documentary      62.809300  117.05  4.13  6280.93   100       7.500500  14.89
Drama            60.889300  118.34  4.36  6088.93   100       7.368200  14.99
Romance          65.063562  118.36  3.32  4749.64    73       7.720411  14.97
Sci-Fi           63.420105  119.88  0.15  6024.91    95       7.745895  14.85
Thriller         59.905342  119.66  2.60  4373.09    73       7.164795  14.64

                                revenue_millions
              min     sum count             mean    max   min      sum count
genre
Action       0.03  636.57    87        24.457471  47.43  0.82  2127.80    87
Comedy       0.19  534.90    72        26.789444  49.81  3.28  1928.84    72
Documentary  0.01  750.05   100        23.796800  49.67  0.38  2379.68   100
Drama        0.07  736.82   100        25.032100  49.57  0.84  2503.21   100
Romance      0.01  563.59    73        26.490137  48.57  0.90  1933.78    73
Sci-Fi       0.24  735.86    95        26.303263  49.47  0.72  2498.81    95
Thriller     0.19  523.03    73        24.846438  47.16  0.14  1813.79    73

In [51]:
#46. Perform named aggregations on content_type.
df.groupby("content_type").agg(avg_revenue =("revenue_millions","mean"),
                               count_content_id=("content_id","count"))

              avg_revenue  count_content_id
content_type
Movie           25.066267               367
TV Show         25.693519               233

In [52]:
#47. Perform named aggregations on country.
df.groupby("country").agg(sub_plan_count=("subscription_plan","count"),
                          views_avg=("views_millions","mean"),
                          revenue=("revenue_millions","sum"))

           sub_plan_count  views_avg  revenue
country
Australia             134  61.122836  3273.54
Canada                120  60.190083  3304.62
India                 121  61.958017  3306.62
UK                    124  59.079194  2966.19
USA                   101  66.059901  2334.94

In [60]:
#48. Extract year from added_date.
df["added_date"]=pd.to_datetime(df["added_date"])
df["year"]=df["added_date"].dt.year
df["year"]

0      2022
1      2023
2      2023
3      2023
4      2024
       ...
595    2023
596    2023
597    2024
598    2023
599    2022
Name: year, Length: 600, dtype: int32

In [62]:
#49. Extract month from added_date.
df["month"]=df["added_date"].dt.month
df["month"]

0       8
1       3
2      10
3       9
4       1
       ..
595     6
596     3
597     2
598    11
599     3
Name: month, Length: 600, dtype: int32

In [63]:
#50. Extract month name from added_date.
df["month_name"]=df["added_date"].dt.month_name()
df["month_name"]

0         August
1          March
2        October
3      September
4        January
         ...
595         June
596        March
597     February
598     November
599        March
Name: month_name, Length: 600, dtype: object

In [65]:
#51. Extract day name from added_date.
df["day_name"]=df["added_date"].dt.day_name()
df["day_name"]

0         Sunday
1       Thursday
2       Thursday
3         Monday
4         Friday
         ...
595     Saturday
596       Friday
597    Wednesday
598      Tuesday
599     Saturday
Name: day_name, Length: 600, dtype: object

In [66]:
#52. Extract quarter from added_date.
df["quarter"]=df["added_date"].dt.quarter
df["quarter"]

0      3
1      1
2      4
3      3
4      1
      ..
595    2
596    1
597    1
598    4
599    1
Name: quarter, Length: 600, dtype: int32

In [67]:
#53. Group data by year and count content added.
df.groupby("year")["year"].count()

year
2021    191
2022    168
2023    183
2024     58
Name: year, dtype: int64

In [68]:
#54. Group data by month name and calculate average views.
df.groupby("month_name")["views_millions"].mean()

month_name
April        53.650517
August       59.686579
December     61.954167
February     65.564400
January      57.761587
July         61.625333
June         59.436744
March        60.893235
May          67.527609
November     63.271750
October      62.048723
September    68.968462
Name: views_millions, dtype: float64

In [69]:
#55. Group data by quarter and calculate average revenue.
df.groupby("quarter")["revenue_millions"].mean()

quarter
1    25.516575
2    25.243333
3    25.247445
4    25.168444
Name: revenue_millions, dtype: float64

In [70]:
#56. Group data by day name and count content added.
df.groupby("day_name")["day_name"].count()

day_name
Friday       95
Monday       76
Saturday     89
Sunday       87
Thursday     94
Tuesday      83
Wednesday    76
Name: day_name, dtype: int64

In [72]:
#57. Identify the month with highest content additions.
df.groupby("month")["month"].count().idxmax()

np.int32(3)

In [75]:
#58. Identify the quarter with highest average imdb_rating.
df.groupby("quarter")["imdb_rating"].mean().idxmax()

np.int32(4)

In [76]:
#59. Group by year and genre and calculate average imdb_rating.
df.groupby(["year","genre"])["imdb_rating"].mean()

year  genre
2021  Action         6.991304
      Comedy         7.358824
      Documentary    6.146667
      Drama          7.045161
      Romance        6.840000
      Sci-Fi         7.585185
      Thriller       6.929167
2022  Action         6.986957
      Comedy         6.687500
      Documentary    6.927586
      Drama          7.057143
      Romance        6.863158
      Sci-Fi         6.850000
      Thriller       5.835000
2023  Action         7.075862
      Comedy         6.995833
      Documentary    7.192308
      Drama          7.004348
      Romance        6.578261
      Sci-Fi         7.136364
      Thriller       6.985000
2024  Action         6.950000
      Comedy         6.680000
      Documentary    6.180000
      Drama          7.470000
      Romance        7.300000
      Sci-Fi         7.137500
      Thriller       6.880000
Name: imdb_rating, dtype: float64

In [77]:
#60. Group by language and year and calculate content count.
df.groupby(["language","year"]).size()

language   year
English    2021    29
           2022    37
           2023    29
           2024     8
Hindi      2021    36
           2022    29
           2023    28
           2024    11
Kannada    2021    29
           2022    25
           2023    24
           2024     6
Malayalam  2021    29
           2022    24
           2023    36
           2024    17
Tamil      2021    36
           2022    28
           2023    40
           2024     7
Telugu     2021    32
           2022    25
           2023    26
           2024     9
dtype: int64

In [78]:
#61. Group by country and subscription_plan and calculate average revenue.
df.groupby(["country","subscription_plan"])["revenue_millions"].mean()

country    subscription_plan
Australia  Basic                26.045238
           Mobile               23.060645
           Premium              23.974815
           Standard             24.042353
Canada     Basic                25.299189
           Mobile               25.695667
           Premium              28.850370
           Standard             31.489231
India      Basic                26.711714
           Mobile               30.790769
           Premium              25.912692
           Standard             26.394706
UK         Basic                23.178462
           Mobile               24.560645
           Premium              24.643235
           Standard             23.149000
USA        Basic                25.274400
           Mobile               25.746296
           Premium              18.653043
           Standard             22.265769
Name: revenue_millions, dtype: float64

In [83]:
#62. Filter grouped years with more than 100 contents.
content=df.groupby("year").size()
content[content>100]

year
2021    191
2022    168
2023    183
dtype: int64

In [85]:
#63. Filter grouped genres with average revenue above 20 million.
df[df["revenue_millions"]>20].groupby("genre")["revenue_millions"].mean()

genre
Action         32.935000
Comedy         33.834902
Documentary    34.100179
Drama          34.368621
Romance        34.680851
Sci-Fi         35.940000
Thriller       33.721489
Name: revenue_millions, dtype: float64